### PR TITLE
fixes #63 Kafka client classes implementation

### LINKED ISSUE #63: MessageConverter and related implementation use Vert.x Kafka client classes
After moving to use the Vert.x Kafka Client, the MessageConverter and related implementation should use the record classes provided from the Vert.x Kafka Client and not from the native Kafka client anymore.

### PR DESCRIPTION
**Pull request by pushpithaDilhan**
fixes #63

### CODE REVIEW

**Comment by ppatierno** [comment]
@pushpithaDilhan I really don't understand why you are opening and closing PRs (4 up to now) to fix the same. We started the discussion in the PR #95 and I asked for changes then you made them ... why not continue on PR #95 ?

**Comment by pushpithaDilhan** [comment]
@ppatierno sorry, I had a indentation problem with my IDE. I think now its fixed

**Comment by ppatierno** [comment]
@pushpithaDilhan I can understand that but why opening different PRs ? You can do the same on the PR #95 because we have the history of our discussions and fixed to apply.

**Comment by pushpithaDilhan** [comment]
@ppatierno I thought it will be a problem to have more commits in one PR. I wanted to take them all to one commit.

**Comment by ppatierno** [comment]
@pushpithaDilhan ok I got it. When you open a PR with some commits and then people ask you some changes, you can just do other commits on the branch you are using for the PR; the PR will be updated automatically. If people ask to you to have just one commit, you can use the `git squash` command for doing that but always using the same PR. It's fine for now, it happens when how Git works is not clear ;)

**Comment by pushpithaDilhan** [comment]
@ppatierno Thanks, this won't happen again. :)

**Comment by ppatierno** [comment]
@pushpithaDilhan all the tests are running fine right ? Did you fix the problem with mocks ?

**Comment by pushpithaDilhan** [comment]
@ppatierno yes it is fixed now. All the tests in Mock passed.

**Comment by pushpithaDilhan** [comment]
Thanks :)

**Pull request merged**
